from . import estudiante_controller
from . import matricula_controller
from . import credencial_apoderado_controller
from . import padres_estudiantes_controller
from . import estudiante_padres_controller
from . import horario_controller
from . import nota_controller
from . import nota_materia_controller
from . import chat_controller
